CREATE TABLE IF NOT EXISTS `td_bbs` (
  `bbs_id` INT  NOT NULL AUTO_INCREMENT, 
  `user_id` VARCHAR(50) NOT NULL,
  `title` VARCHAR(150) NOT NULL, 
  `contents` MEDIUMTEXT NOT NULL, 
  `view_cnt` INT DEFAULT 0, 
  `reply_cnt` INT DEFAULT 0, 
  `reg_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (bbs_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;