CREATE TABLE IF NOT EXISTS `td_bbsreply` (
  `reply_id` INT  NOT NULL AUTO_INCREMENT, 
  `bbs_id` INT NOT NULL, 
  `user_id` VARCHAR(50) NOT NULL,
  `contents` MEDIUMTEXT NOT NULL, 
  `reg_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  PRIMARY KEY (reply_id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;